<?php
	require_once("$_SERVER[DOCUMENT_ROOT]/librerias/propias/php/apariencia.php");
	require_once("$_SERVER[DOCUMENT_ROOT]/librerias/propias/php/base.php");
	require_once("$_SERVER[DOCUMENT_ROOT]/librerias/propias/php/guardar.php");
	require_once("$_SERVER[DOCUMENT_ROOT]/librerias/propias/php/encriptacion.php");
	require_once("$_SERVER[DOCUMENT_ROOT]/librerias/propias/php/manejo_texto.php");
	require_once("$_SERVER[DOCUMENT_ROOT]/librerias/propias/php/manejo_visita.php");
	require_once("$_SERVER[DOCUMENT_ROOT]/modulos/buscador/traer_lista.php");
	require_once("$_SERVER[DOCUMENT_ROOT]/modulos/buscador/traer_titulo.php");
	require_once("$_SERVER[DOCUMENT_ROOT]/modulos/buscador/traer_formulario.php");
?>